Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/DoubleNegation:
  Description: 'Checks for uses of double negation (!!).'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-bang-bang'
  Enabled: false
